version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: safaschat-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: safaschat
      MYSQL_USER: local
      MYSQL_PASSWORD: development
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - safaschat-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --max-connections=200

volumes:
  mariadb_data:
    driver: local

networks:
  safaschat-network:
    driver: bridge